### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by TomTasche** [opendocument-app/OpenDocument.droid#110]
android:forceDarkAllowed="true" - https://developer.android.com/preview/features/darktheme

**Comment by TomTasche** [comment]
android:forceDarkAllowed is set to true now. Implementing a custom toggle for dark mode would require a lot of work as we would need to style the WebView accordingly too...

**Comment by TomTasche** [comment]
Would be possible using AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES); but we need to implement a setting in the menu for that.

**Comment by ioshomebrew** [comment]
Hi, I'm looking into possibly implementing dark mode, and I have some questions, would it apply to the home screen and/or the text editor?

**Comment by TomTasche** [comment]
Hi Katie, this would apply to all parts of the app. Since users spend the most time in this app while viewing a document, it's our main focus to implement dark mode there. So yes, it would have to be applied to the "text editor" too. Let me know if there's anything I can do to help you with this task!

**Comment by ioshomebrew** [comment]
Ok, thanks
