### ISSUE TITLE
Add support to read OOXML documents

### ISSUE THREAD

**Issue by brunoarruda** [opendocument-app/OpenDocument.droid#125]
Hi,

Is it inside the scope of this app to add support to files with the XML Microsoft standard (OOXML) too?

That would increase the usability of your app and would also commit to the ideia of being compatible with open standards of documents. 

If you agree, I can work on a PR on the subject.

Regards,

Bruno.

**Comment by TomTasche** [comment]
Hi Bruno,

Yes, that's definitely something we're interested in because a surprisingly big chunk of our users is already using our app to do that. At the moment we only support that by uploading documents to the cloud and using an online document viewer to render the file.

My colleague already started working on a prototype for this in C++: https://github.com/andiwand/OpenDocument.core/tree/feature/doc?files=1

Are you familiar with C++? I'm sure he'd love to point you in the right direction to work on this.

**Comment by brunoarruda** [comment]
Hi,

I'm more familiar with Java than C++.  I understand code written on it, but I don't know the common libraries and facilities available for the language, and I could need to review memory access, manipulation and management. So (I guess) it will took some time from now (+3 months) for me to be that familiar with it.

By the way, could you point the reason for you guys to work with C++ on an android context? There are performance issues related to java native libraries?

I thought using a java reliable library to process the file, something like [Apache POI](https://poi.apache.org/). I don't know if their [Apache licence](https://poi.apache.org/legal.html) conflicts with your [GNU license](https://github.com/TomTasche/OpenDocument.droid/blob/master/LICENSE), but in such a case I could search other libraries to work.

**Comment by TomTasche** [comment]
Reason we're using C++ is performance and interoperability (we do have an iOS app now too).

Using libraries like POI has the disadvantage of an increased app size. Our app aims to be as small as possible. Moreover, POI is not available for iOS as far as I know?

We'd be happy to assist you in getting to know C++ and also pay some money if you finish the task in a scope that we can define beforehand.

**Comment by brunoarruda** [comment]
Oh, it's a good reason. I didn't notice you've launched it for iOS, so it's better not to work with POI anymore :sweat_smile:

Thanks for the opportunity, I'm very interested. Do you use slack or other channel for discussions related to the app? I guess it's better to get out of this issue until we mature the idea and define what needs to be done.

If some of you use telegram, just call me [here](https://t.me/arrudabruno).

**Comment by TomTasche** [comment]
Done: https://github.com/opendocument-app/OpenDocument.droid/commit/5b6de31467009f0def437bb23b3deca0c31724ca
