### ISSUE TITLE
Better content for the "Recent documents list" dialog

### ISSUE THREAD

**Issue by ldmpub** [opendocument-app/OpenDocument.droid#177]
Hi,

2 improvements on the "recent documents list" content:
- automatically add to this list each saved document (it will ease it's re-opening)
- automatically remove from this list documents for which last load has failed (because not found on the device)

Thanks,

**Comment by TomTasche** [comment]
Thanks for your suggestions! I though the second suggestion was already implemented, but I'll double check to make sure. Never thought of the first suggestion although it's really obvious.

**Comment by TomTasche** [comment]
Believe it or not, but I've implemented both of your suggestions now. I need to fix some other things first before releasing it, but I wanted to give you a heads-up already that this is being worked on!

**Comment by ldmpub** [comment]
Well done.
