### ISSUE TITLE
Reading position of about dialog gets lost after device rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [opendocument-app/OpenDocument.droid#185]
See the pics

![Screen Shot 2020-08-08 at 11 05 08 PM](https://user-images.githubusercontent.com/67744580/89713701-0776bf80-d9cc-11ea-9d09-a2e973026464.png)
![Screen Shot 2020-08-08 at 11 05 21 PM](https://user-images.githubusercontent.com/67744580/89713702-09408300-d9cc-11ea-92ce-02621be2b28f.png)

**Comment by TomTasche** [comment]
Hi,

Looks like you're using a very old version of our app. Have you checked the Play Store for updates? The latest version is also available via our GitHub repository if you don't want to use Play Store.

Greetings
Tom
