### ISSUE TITLE
Some error occure during build project

### ISSUE THREAD

**Issue by MURTAZA5** [opendocument-app/OpenDocument.droid#190]
> Task :prepareKotlinBuildScriptModel UP-TO-DATE
D:\Uni Danish projects\OpenDocument.droid-master\CMakeLists.txt : C/C++ liteDebug|x86 : CMake Error at D:\Uni Danish projects\OpenDocument.droid-master\CMakeLists.txt:15 (add_subdirectory):
  The source directory

    D:/Uni Danish projects/OpenDocument.droid-master/OpenDocument.core

  does not contain a CMakeLists.txt file.

D:\Uni Danish projects\OpenDocument.droid-master\CMakeLists.txt : C/C++ liteDebug|x86 : Configuration failed.
executing external native build for cmake D:\Uni Danish projects\OpenDocument.droid-master\CMakeLists.txt

 error in cmake.txt file of that two lines
add_subdirectory(OpenDocument.core)
target_link_libraries(odr-core odr-shared)

**Comment by TomTasche** [comment]
Have you run "git submodule update --init --recursive" after cloning the repository?
