### ISSUE TITLE
Doesn't open excel sheets

### ISSUE THREAD

**Issue by meximan** [opendocument-app/OpenDocument.droid#204]
I am trying to open an excel sheet (.xlsx) but the app never opens it (white screen).

I'd like to use this app exclusively instead of WPSOffice (full of crap ads, trackers etc). Any suggestions?

**Comment by TomTasche** [comment]
Hi there,

We're currently working on supporting XLSX offline. For the time being, it's only supported by uploading the document *temporarily* to our server and rendering it there. Of course, you should not be seeing a white screen in that case... Is there a chance you could share the document privately with me via support@opendocument.app?

Greetings
Tom

**Comment by meximan** [comment]
Yes will do today.

**Comment by meximan** [comment]
Done.

**Comment by Elaborendum** [comment]
I'm also experiencing this same issue, but I can't open presentations either. The latest F-Droid version doesn't seem to have internet access permission

**Comment by TomTasche** [comment]
> I'm also experiencing this same issue, but I can't open presentations either. The latest F-Droid version doesn't seem to have internet access permission

I'm not maintaining the version published on F-Droid, so you would need to file a bug with them. Feel free to link to this issue though so they can reach out for help if necessary.

**Comment by meximan** [comment]
Also what did you think of the file I sent you?

**Comment by TomTasche** [comment]
Hi, here's my reply to your email:

> For me the document loads after the dialog shows up that asks to upload the document. As I've mentioned before, the app does not support XLSX natively at the moment, but needs to upload the file to our server temporarily first. Can you confirm that this is how it works for you too? If not, please send a screenshot of what you're seeing.

Yes, we are working on offline XLSX support, which would most likely solve your issue! I'd still be interested to investigate your current issue if possible.

**Comment by meximan** [comment]
How do I upload to server and do the entire process?

**Comment by TomTasche** [comment]
That should happen automatically. As soon as you open an unsupported file format the app asks you to upload the file in order to display it. Are you using the latest version from Google Play?

**Comment by meximan** [comment]
I don't like the Google play one. It hasn't been updated since May 2021. While the fdroid, doesn't have ads and it was updated 2 months ago. I continue getting a blank screen when opening files

**Comment by TomTasche** [comment]
I don't maintain the version on F-Droid, so I can't say what's wrong there. I assume they removed some functionality. You could use the Pro version from the Google Play store instead, which does not include ads.

**Comment by meximan** [comment]
Who updated the fdroid version 2 months ago?
