### ISSUE TITLE
OpenDocument.droid/app/src/main/cpp/CoreWrapper.cpp:4:10: fatal error: 'odr/Config.h' file not found

### ISSUE THREAD

**Issue by hoangchungk53qx1** [opendocument-app/OpenDocument.droid#209]
how to add file from OpenDocument.core
![Screen Shot 2021-11-11 at 01 50 38](https://user-images.githubusercontent.com/52132635/141174943-af1e57fa-1878-4b95-a10e-f105444fd1dd.png)

**Comment by TomTasche** [comment]
Have you checked out submodules? `git submodule update --recursive --init`
