### ISSUE TITLE
Parsing apk file failed

### ISSUE THREAD

**Issue by VasiliyArkhipov2** [opendocument-app/OpenDocument.droid#214]
Running GrapheneOS with Android 12, tried to install latest version via F-Droid. Results in an error: Maybe minSdk of apk is lower than current Sdk? Prior version installs without problems.

**Comment by TomTasche** [comment]
Sorry to hear that, but we're not maintaining F-Droid builds ourselves. F-Droid is doing that.

However, we solved a similar issue in our last Play Store update so I'd assume F-Droid is going to pick that up soon too.
