### ISSUE TITLE
New paragraphs (line break / carriage return) are not respected in docx

### ISSUE THREAD

**Issue by axelsimon** [opendocument-app/OpenDocument.droid#216]
Hello,

I understand the app is designed for Open Document formats, not MS formats. However, just to see what would happen, i just tested the app on a simple docx file, to see if it could also open it.

It did, but the (very basic) formatting is messed up: the new lines that separate paragraphs are missing, but some other new lines are respected. In any case, the text is hard to read.

I tested opening the same docx file with the old LibreOffice Viewer (not updated in years) and the paragraphs show normally.
This might be an issues in the underlying library.

Thanks!

**Comment by andiwand** [comment]
hey @axelsimon, thank you for your feedback!

I am working on the library behind the application.

could you share the docx file with us? we need it to improve the formatting and additionally we can use it to prevent regression in the future.

if you do not want to share the file publicly you can also email it to me

thanks!

**Comment by axelsimon** [comment]
Sorry I never got round to sharing the doc. If I come across another one with the same issue I'll share here and ask to reopen the issue.
