### ISSUE TITLE
F-Droid Package Error

### ISSUE THREAD

**Issue by tcables** [opendocument-app/OpenDocument.droid#218]
Hello, thank you for your great work on this project!

I am seeing an error when updating or fresh installing the app from F-Droid:

`Error installing LibreOffice &
OpenOffice document reader | ODF

Parsing apk file failed!Maybe minSdk of apk
is lower than current Sdk?Look into logcat
for more specific warnings of Android's
PackageParser`

I'm running Android 12, (GrapheneOS) on a pixel 3.

I tried to pull a logcat but couldn't figure out how to get it to show the logs for the package parser.

**Comment by TomTasche** [comment]
Hi there,

I can only offer the same answer as for other F-Droid issues unfortunately: https://github.com/opendocument-app/OpenDocument.droid/issues/214

Greetings
Tom
