### ISSUE TITLE
PDF annotations not shown

### ISSUE THREAD

**Issue by markwmuller** [opendocument-app/OpenDocument.droid#219]
Thanks for a cool app! 

I use XODO pdf to mark up PDFs using a stylus, for example the attached PDF. Almost all PDF viewers render this correctly, but OpenOffice viewer does not (it only shows the base PDFs, not the annotations).

[test-Copy-Reduced.pdf](https://github.com/opendocument-app/OpenDocument.droid/files/7891706/test-Copy-Reduced.pdf)

I'm using version 3.12, installed via F-Droid on a phone with Android 11

**Comment by TomTasche** [comment]
Thanks a lot for your report, that's a good observation! I've reported the issue to the library that we're using to render PDFs.

**Comment by TomTasche** [comment]
Going to be released with the next update! Thanks to @ViliusSutkus89 :clap:
