### ISSUE TITLE
Cannot install v3.12 on Android 12

### ISSUE THREAD

**Issue by tifriis208** [opendocument-app/OpenDocument.droid#233]
Hi,

I run 3.10.4 from f-droid on Grapheneos (Android 12). When trying to update to v3.12, I got this error:
![Screenshot_20220124-070011](https://user-images.githubusercontent.com/40381365/150730310-9ec8d55f-2786-4c16-8b39-7856d2fdde59.png)

I can send logs if somebody explain me how to do. Thanks :)

**Comment by TomTasche** [comment]
Hi there,

I can only offer the same answer as for other F-Droid issues unfortunately: #214

Greetings
Tom

**Comment by tifriis208** [comment]
Thanks for your reply ! I will try to inform fdroid
