### ISSUE TITLE
libodr is incompatible with aarch64linux

### ISSUE THREAD

**Issue by FunkyMuse** [opendocument-app/OpenDocument.droid#241]
Hello, when trying to build the project on Mac M1 chip

I'm getting this error

```c++
C/C++: ld: error: /Users/hidden/.conan/data/odrcore/2.1.2/_/_/package/bd8726e5c6f0f21f8f3bb48028acca8850601171/lib/libodr.a(style.cpp.o) is incompatible with aarch64linux
```

**Comment by TomTasche** [comment]
Are you building the Android app or are you trying to build our core directly? I don't see why it would attempt to build that particular architecture...

**Comment by FunkyMuse** [comment]
> Are you building the Android app or are you trying to build our core directly? I don't see why it would attempt to build that particular architecture...

When I'm trying to build the app it hangs in crypto cryptopp/8.5.0

**Comment by almuntsr** [comment]
hi 

plz fix 
 ERROR: Unable to find 'odr/2.1.2' in remotes

**Comment by almuntsr** [comment]
plz 
fix 
 ERROR: Unable to find 'odrcore/2.1.2' in remotes
