### ISSUE TITLE
Question: Diffrent size of apk of fdroid and playstore

### ISSUE THREAD

**Issue by Jrchintu** [opendocument-app/OpenDocument.droid#257]
Hello developer, 
    Thanks for this app. Recently i noticed that size of apk on playstore is nearly 22.40 Mb but on fdroid its 59.3 Mb. Can you please explain why there is diffrence in size. Is it due to less feature's* or due to diffrent compression used by google. Thanks

**Comment by TomTasche** [comment]
That's a great question, but I can't answer it reliably as I'm not responsible for the version of our app hosted on F-Droid. Your guess seems pretty accurate though: the Google Play Store is using a different compression technique (AAB).
