### ISSUE TITLE
Add F-Droid badge

### ISSUE THREAD

**Issue by PanderMusubi** [opendocument-app/OpenDocument.droid#266]
On https://opendocument.app/ please add an F-Droid badge with a link to https://f-droid.org/en/packages/at.tomtasche.reader/

For information on F-Droid badges, see https://gitlab.com/fdroid/artwork/tree/master/badge#designs

Unfortunately, at the moment we do not have 1-bit version (black and whilte).

**Comment by TomTasche** [comment]
Our researchers have been working on this ticket for the last two years now and I can gladly announce that they have found an innovative solution powered by AI.

Just kidding, squeezed the badge in now: https://opendocument.app/

Thanks for the report!
