### ISSUE TITLE
cryptopp/8.5.0: Error in build() method, line 94

### ISSUE THREAD

**Issue by almuntsr** [opendocument-app/OpenDocument.droid#288]
cryptopp/8.5.0: Error in build() method, line 94
### 
ERROR: cryptopp/8.5.0: Error in build() method, line 94
cmake = self._configure_cmake()
while calling '_configure_cmake', line 89
self._cmake.configure(build_folder=self._build_subfolder)

**cryptopp/8.5.0: Error in build() method, line 94**

**Comment by andiwand** [comment]
Seems unrelated to `odr.droid`. Closing
