### ISSUE TITLE
Shows in open with context for contacts

### ISSUE THREAD

**Issue by fugkco** [opendocument-app/OpenDocument.droid#314]
Hi,

This app seems to show as an option when clicking the number attributes for contacts. E.g. when opening a contact, and clicking the call/video call/text button, it gives ODR as an option. ODR has no way of opening the number, but apps like Signal, WhatsApp, and Telegram do of course. Is it possible to dissociate ODR from numbers?

Thanks

**Comment by TomTasche** [comment]
Hi,

Yes, there is a solution for that: https://github.com/opendocument-app/OpenDocument.droid/issues/203#issuecomment-906242339

Sorry for the inconvenience!

Greetings
Tom
