### ISSUE TITLE
ERROR: pugixml/1.11: Cannot load recipe.

### ISSUE THREAD

**Issue by jehadmashhour** [opendocument-app/OpenDocument.droid#323]
Hello,

Could you please tell me how I can fix this issue ?

ERROR: pugixml/1.11: Cannot load recipe.
Error loading conanfile at '/Users/jehadabdalqader/.conan/data/pugixml/1.11/_/_/export/conanfile.py': Current Conan version (1.50.0) does not satisfy the defined one (>=1.54.0).
CMake Error at app/conan.cmake:633 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  CMakeLists.txt:25 (conan_cmake_install)

**Comment by TomTasche** [comment]
> Current Conan version (1.50.0) does not satisfy the defined one (>=1.54.0).

Sounds like it doesn't like your version of Conan!

**Comment by jehadmashhour** [comment]
Thanks for your response @TomTasche 

Sorry I'm not familiar with conan , I have updated its version to 1.58 then tried to run the project but I faced another error :

ERROR: cryptopp/8.5.0: Error in generate() method, line 111
	tc.generate()
	ConanException: CMakeToolchain needs tools.android:ndk_path configuration defined
CMake Error at app/conan.cmake:633 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  CMakeLists.txt:25 (conan_cmake_install)

**Comment by andiwand** [comment]
Seems unrelated to `odr.droid`. Closing
