### ISSUE TITLE
Tables don't render properly

### ISSUE THREAD

**Issue by LavellanDWR** [opendocument-app/OpenDocument.droid#354]
Tables don't render correctly in .docx files. Only the first column is visible.

**Comment by andiwand** [comment]
@TomTasche for DOCX we use the core backend right? That might be an actual bug in core in this case.

@LavellanDWR are you able to share a file so we can reproduce this? Or does this happen with all of your files?

**Comment by TomTasche** [comment]
> @TomTasche for DOCX we use the core backend right? That might be an actual bug in core in this case.

Correct!

**Comment by LavellanDWR** [comment]
> @TomTasche for DOCX we use the core backend right? That might be an actual bug in core in this case.
> 
> @LavellanDWR are you able to share a file so we can reproduce this? Or does this happen with all of your files?

Here! A few sample tables and screenshots of what they look like in the app.
The other columns get displayed far off on the other side of the document.

[tabletest.docx](https://github
![xb08ed8pjguolxf5](https://github.com/opendocument-app/OpenDocument.droid/assets/89345735/0326f084-29e1-4b5f-8f85-dad6e52f9f10)
![52fzxvv6bjya1ajb](https://github.com/opendocument-app/OpenDocument.droid/assets/89345735/e046bf48-3332-4003-955e-1fb9a592b561)
.com/user-attachments/files/15787721/tabletest.docx)

**Comment by TomTasche** [comment]
@andiwand I guess this is an issue for the core? As we know from ODT already, tables are a pain though...

**Comment by andiwand** [comment]
Should be fixed with https://github.com/opendocument-app/OpenDocument.core/pull/370 which has to be consumed by a newer version of the core here

**Comment by TomTasche** [comment]
This is (slowly) rolling out now!
