### ISSUE TITLE
Please release apk on GitHub so that it can be installed with Obtainium

### ISSUE THREAD

**Issue by lamyergeier** [opendocument-app/OpenDocument.droid#372]
Last released apk is version 3.24

![Screenshot_20240914_015326.jpg](https://github.com/user-attachments/assets/da9ca198-e4b2-41e6-a970-fd290986b6c7)

**Comment by TomTasche** [comment]
Thanks for the reminder, here you go: https://github.com/opendocument-app/OpenDocument.droid/releases/tag/v3.31
